package com.persistentbit.core.tokenizer;

import com.persistentbit.core.utils.BaseValueClass;

/**
 * A token generated by a Tokenizer like {@link SimpleTokenizer}.
 * @author Peter Muys
 */
public class Token<TT> extends BaseValueClass {
    /**
     * The position of the token in the file
     */
    public final Pos pos;
    /**
     * The type Id of the token (user defined)
     */
    public final TT  type;
    /**
     * The text from the source that forms the token.
     */
    public final String text;

    public Token(Pos pos, TT type, String text) {
        this.pos = pos;
        this.type = type;
        this.text = text;
    }
}
